import type { Obra, Tarefa, Insumo, CustoHistorico, KPIs } from '@/types'

export const mockObras: Obra[] = [
  {
    id: '1',
    nome: 'Residencial Vila Nova – Bloco A',
    descricao: 'Construção de edifício residencial de 8 andares com 32 apartamentos',
    data_inicio: '2024-01-15',
    data_fim_previsto: '2025-06-30',
    orcamento_total: 4800000,
    custo_real: 3120000,
    progresso_total: 65,
    status: 'em_andamento',
    responsavel: 'Eng. Carlos Mendes',
    localizacao: 'Rua das Palmeiras, 450 – São Paulo',
  },
  {
    id: '2',
    nome: 'Centro Comercial Horizonte',
    descricao: 'Reforma e expansão de centro comercial com 48 lojas',
    data_inicio: '2024-03-01',
    data_fim_previsto: '2024-12-31',
    orcamento_total: 2200000,
    custo_real: 2450000,
    progresso_total: 82,
    status: 'em_andamento',
    responsavel: 'Eng. Ana Lima',
    localizacao: 'Av. Industrial, 1200 – Campinas',
  },
  {
    id: '3',
    nome: 'Galpão Logístico Norte',
    descricao: 'Construção de galpão industrial de 6.000 m²',
    data_inicio: '2024-06-01',
    data_fim_previsto: '2025-02-28',
    orcamento_total: 1600000,
    custo_real: 480000,
    progresso_total: 28,
    status: 'em_andamento',
    responsavel: 'Eng. Pedro Alves',
    localizacao: 'Rod. Anhanguera, Km 45 – Jundiaí',
  },
]

export const mockTarefas: Tarefa[] = [
  {
    id: 't1',
    obra_id: '1',
    projeto: 'Projeto 1 - Estrutura',
    nome: 'Concretar Pilares – Térreo',
    descricao: 'Concretagem dos 12 pilares do pavimento térreo',
    responsavel: 'Equipe Estrutural A',
    data_inicio: '2024-10-01',
    data_fim_previsto: '2024-10-15',
    percentual_conclusao: 100,
    status: 'concluido',
    peso: 3,
    sub_tarefas: [
      { id: 't1-1', obra_id: '1', projeto: 'Projeto 1 - Estrutura', parent_id: 't1', nome: 'Armação dos pilares', descricao: '', responsavel: 'José Silva', data_inicio: '2024-10-01', data_fim_previsto: '2024-10-05', percentual_conclusao: 100, status: 'concluido', peso: 1 },
      { id: 't1-2', obra_id: '1', projeto: 'Projeto 1 - Estrutura', parent_id: 't1', nome: 'Montagem de fôrmas', descricao: '', responsavel: 'Equipe B', data_inicio: '2024-10-05', data_fim_previsto: '2024-10-09', percentual_conclusao: 100, status: 'concluido', peso: 1 },
      { id: 't1-3', obra_id: '1', projeto: 'Projeto 1 - Estrutura', parent_id: 't1', nome: 'Concretagem', descricao: '', responsavel: 'Equipe A', data_inicio: '2024-10-09', data_fim_previsto: '2024-10-12', percentual_conclusao: 100, status: 'concluido', peso: 1 },
      { id: 't1-4', obra_id: '1', projeto: 'Projeto 1 - Estrutura', parent_id: 't1', nome: 'Desforma', descricao: '', responsavel: 'Equipe B', data_inicio: '2024-10-12', data_fim_previsto: '2024-10-15', percentual_conclusao: 100, status: 'concluido', peso: 1 },
    ],
  },
  {
    id: 't2',
    obra_id: '1',
    projeto: 'Projeto 2 - Alvenaria',
    nome: 'Alvenaria – 3º Andar',
    descricao: 'Levantamento das paredes de alvenaria no 3º pavimento',
    responsavel: 'Equipe Alvenaria',
    data_inicio: '2024-11-01',
    data_fim_previsto: '2024-11-30',
    percentual_conclusao: 75,
    status: 'em_andamento',
    peso: 2,
  },
  {
    id: 't3',
    obra_id: '1',
    projeto: 'Projeto 3 - Instalações',
    nome: 'Instalações Elétricas – 1º ao 3º',
    descricao: 'Passagem de eletrodutos e fiação nos primeiros 3 andares',
    responsavel: 'Equipe Elétrica',
    data_inicio: '2024-11-10',
    data_fim_previsto: '2024-12-05',
    percentual_conclusao: 40,
    status: 'em_andamento',
    peso: 2,
  },
  {
    id: 't4',
    obra_id: '1',
    projeto: 'Projeto 0 - Fundação',
    nome: 'Impermeabilização Fundação',
    descricao: 'Aplicação de manta asfáltica na fundação',
    responsavel: 'Subempreiteiro Hidro',
    data_inicio: '2024-10-20',
    data_fim_previsto: '2024-10-25',
    percentual_conclusao: 20,
    status: 'atrasado',
    peso: 2,
  },
  {
    id: 't5',
    obra_id: '1',
    projeto: 'Projeto 4 - Fachada',
    nome: 'Revestimento Fachada',
    descricao: 'Aplicação de pastilhas cerâmicas na fachada frontal',
    responsavel: 'Equipe Revestimento',
    data_inicio: '2025-01-15',
    data_fim_previsto: '2025-03-30',
    percentual_conclusao: 0,
    status: 'pendente',
    peso: 2,
  },
  {
    id: 't6',
    obra_id: '1',
    projeto: 'Projeto 1 - Estrutura',
    nome: 'Estrutura Cobertura',
    descricao: 'Montagem da estrutura metálica de cobertura',
    responsavel: 'Equipe Metálica',
    data_inicio: '2025-02-01',
    data_fim_previsto: '2025-04-15',
    percentual_conclusao: 0,
    status: 'pendente',
    peso: 3,
  },
]

export const mockInsumos: Insumo[] = [
  { id: 'i1', obra_id: '1', tarefa_id: 't1', nome: 'Concreto usinado fck 25', unidade: 'm³', quantidade_prevista: 85, quantidade_real: 87.5, custo_unitario: 420, fornecedor: 'Concrelev', categoria: 'Concreto' },
  { id: 'i2', obra_id: '1', tarefa_id: 't1', nome: 'Aço CA-50 12,5mm', unidade: 'kg', quantidade_prevista: 3200, quantidade_real: 3350, custo_unitario: 8.50, fornecedor: 'Gerdau', categoria: 'Aço' },
  { id: 'i3', obra_id: '1', tarefa_id: 't1', nome: 'Madeira Pinus p/ Fôrma', unidade: 'm²', quantidade_prevista: 420, quantidade_real: 430, custo_unitario: 45, fornecedor: 'Madeireira Norte', categoria: 'Madeira' },
  { id: 'i4', obra_id: '1', tarefa_id: 't2', nome: 'Bloco cerâmico 14x19x29', unidade: 'un', quantidade_prevista: 18000, quantidade_real: 13500, custo_unitario: 2.80, fornecedor: 'Cerâmica Sul', categoria: 'Alvenaria' },
  { id: 'i5', obra_id: '1', tarefa_id: 't2', nome: 'Argamassa de assentamento', unidade: 'saco', quantidade_prevista: 340, quantidade_real: 255, custo_unitario: 32, fornecedor: 'Votorantim', categoria: 'Argamassa' },
  { id: 'i6', obra_id: '1', tarefa_id: 't3', nome: 'Eletroduto PVC 25mm', unidade: 'm', quantidade_prevista: 1200, quantidade_real: 480, custo_unitario: 4.50, fornecedor: 'Tigre', categoria: 'Elétrico' },
  { id: 'i7', obra_id: '1', tarefa_id: 't3', nome: 'Fio 2,5mm FLEX', unidade: 'm', quantidade_prevista: 3500, quantidade_real: 1400, custo_unitario: 3.20, fornecedor: 'Ficap', categoria: 'Elétrico' },
  { id: 'i8', obra_id: '1', tarefa_id: 't4', nome: 'Manta asfáltica 3mm', unidade: 'm²', quantidade_prevista: 280, quantidade_real: 60, custo_unitario: 28, fornecedor: 'Vedatop', categoria: 'Impermeabilização' },
]

export const mockCustosHistorico: CustoHistorico[] = [
  { mes: 'Jan/24', custo_previsto: 280000, custo_real: 265000 },
  { mes: 'Fev/24', custo_previsto: 310000, custo_real: 298000 },
  { mes: 'Mar/24', custo_previsto: 345000, custo_real: 362000 },
  { mes: 'Abr/24', custo_previsto: 380000, custo_real: 405000 },
  { mes: 'Mai/24', custo_previsto: 420000, custo_real: 438000 },
  { mes: 'Jun/24', custo_previsto: 395000, custo_real: 412000 },
  { mes: 'Jul/24', custo_previsto: 360000, custo_real: 345000 },
  { mes: 'Ago/24', custo_previsto: 390000, custo_real: 415000 },
  { mes: 'Set/24', custo_previsto: 410000, custo_real: 398000 },
  { mes: 'Out/24', custo_previsto: 430000, custo_real: 482000 },
]

export const mockKPIs: KPIs = {
  idc: 0.94,
  idp: 0.88,
  progresso_total: 65,
  custo_real: 3120000,
  orcamento_total: 4800000,
  tarefas_total: 6,
  tarefas_concluidas: 1,
  tarefas_atrasadas: 1,
}

export const mockHistorico = [
  { mes: 'Jan', custo_previsto: 100000, custo_real: 95000 },
  { mes: 'Fev', custo_previsto: 200000, custo_real: 190000 },
  { mes: 'Mar', custo_previsto: 350000, custo_real: 340000 },
  { mes: 'Abr', custo_previsto: 500000, custo_real: 490000 },
  { mes: 'Mai', custo_previsto: 700000, custo_real: 680000 },
  { mes: 'Jun', custo_previsto: 840000, custo_real: 840000 },
]
